### ISSUE TITLE
white result page

### ISSUE THREAD

**Issue by staabm** [kocsismate/php-version-benchmarks#3]
it seems something broke.. its just a white page on https://kocsismate.github.io/php-version-benchmarks/

![grafik](https://user-images.githubusercontent.com/120441/141611630-7998d7dc-db2d-4e90-85a9-4c7951be2f65.png)

**Comment by ohmydevops** [comment]
same problem

![image](https://user-images.githubusercontent.com/21690865/141642702-19d37bbc-b387-41f8-aae3-64dbf6411dfb.png)

**Comment by GreenReaper** [comment]
Indeed, [the ones here work](https://github.com/kocsismate/php-version-benchmarks/tree/main/docs/results) but obviously are not quite up to date.

**Comment by kocsismate** [comment]
I've just changed the URL not to point to the inexistent page.
