### ISSUE TITLE
Incorrect percentage?

### ISSUE THREAD

**Issue by pronskiy** [kocsismate/php-version-benchmarks#5]
Looks like something does not end up here.
I'm looking at Symfony demo app benchmark results, and it says median diff is -30.74%. But in fact, it's 23.5%
1.66990 - 30.74% = 1.15657274 // this !== 1.27731

Could you clarify which one is correct?

**Comment by nikic** [comment]
It's interpreted the other way around: 1.27731 + 30.74% = 1.6699

The easy way to make this interpretation correct is to specify the "speedup": PHP 8.1 is 1.30x faster.

**Comment by kocsismate** [comment]
Uhh, you are right, how embarrassing! I'll double check the code tomorrow, but I must have used the wrong formula to calculate the change. I'll fix it ASAP.

**Comment by kocsismate** [comment]
I've just fixed the difference calculation and retroactively changed the previous results, so the "median diff %" and the "average diff %" labels should be correct now.
