### ISSUE TITLE
Run failure with PHP 8.2

### ISSUE THREAD

**Issue by pingzhaozz** [kocsismate/php-version-benchmarks#8]
I ran './benchmark.sh run local'(Laravel demo) failure on PHP 8.2. It's ok with PHP 7.4 & 8.0. Is it a issue? Or a PHP 8.2 version is required(php-cgi:php_82-latest in the log)?

Commit: c7c28c5769e2

### The error log shows:

Step 14/14 : CMD ["php-cgi"] 
 ---> Running in e18eb2a49b86
Removing intermediate container e18eb2a49b86
 ---> 79ee016749d3
Successfully built 79ee016749d3
Successfully tagged php-cgi:php_82-latest
---------------------------------------------------------------------------------------
Laravel demo app - 1/1 - local - PHP 8.2 (opcache: 1, preloading: 0, JIT: 0)
---------------------------------------------------------------------------------------
[2022-01-27 07:52:13] production.ERROR: Opis\Closure\SerializableClosure implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) {"exception":"[object] (ErrorException(code: 0): Opis\\Closure\\SerializableClosure implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) at /code/app/laravel/vendor/opis/closure/src/SerializableClosure.php:18)
[stacktrace]
#0 /code/app/laravel/vendor/opis/closure/src/SerializableClosure.php(18): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8192, 'Opis\\\\Closure\\\\Se...', '/code/app/larav...', 18)
#1 /code/app/laravel/vendor/composer/ClassLoader.php(571): include('/code/app/larav...')
#2 /code/app/laravel/vendor/composer/ClassLoader.php(428): Composer\\Autoload\\includeFile('/code/app/larav...')
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Opis\\\\Closure\\\\Se...')
#4 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(45): class_exists('Opis\\\\Closure\\\\Se...')
#5 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(19): Illuminate\\Encryption\\EncryptionServiceProvider->registerOpisSecurityKey()
#6 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(672): Illuminate\\Encryption\\EncryptionServiceProvider->register()
#7 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register(Object(Illuminate\\Encryption\\EncryptionServiceProvider))
#8 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(649): Illuminate\\Foundation\\ProviderRepository->load(Array)
#9 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#10 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#11 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#12 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(136): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#13 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#14 /code/app/laravel/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#15 {main}
"}
[2022-01-27 07:52:13] production.ERROR: Target class [view] does not exist. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [view] does not exist. at /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:875)
[stacktrace]
#0 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\\Container\\Container->build('view')
#1 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->resolve('view', Array, true)
#2 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\\Foundation\\Application->resolve('view', Array)
#3 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\\Container\\Container->make('view', Array)
#4 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(1420): Illuminate\\Foundation\\Application->make('view')
#5 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(198): Illuminate\\Container\\Container->offsetGet('view')
#6 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(166): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance('view')
#7 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(255): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#8 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(18): Illuminate\\Support\\Facades\\Facade::__callStatic('replaceNamespac...', Array)
#9 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(584): Illuminate\\Foundation\\Exceptions\\RegisterErrorViewPaths->__invoke()
#10 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(565): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()
#11 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(476): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#12 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(354): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#13 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(426): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(ErrorException))
#14 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(114): Illuminate\\Foundation\\Http\\Kernel->renderException(Object(Illuminate\\Http\\Request), Object(ErrorException))
#15 /code/app/laravel/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#16 {main}

[previous exception] [object] (ReflectionException(code: -1): Class \"view\" does not exist at /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:873)
[stacktrace]
#0 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): ReflectionClass->__construct('view')
#1 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\\Container\\Container->build('view')
#2 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->resolve('view', Array, true)
#3 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\\Foundation\\Application->resolve('view', Array)
#4 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\\Container\\Container->make('view', Array)
#5 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(1420): Illuminate\\Foundation\\Application->make('view')
#6 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(198): Illuminate\\Container\\Container->offsetGet('view')
#7 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(166): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance('view')
#8 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(255): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#9 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(18): Illuminate\\Support\\Facades\\Facade::__callStatic('replaceNamespac...', Array)
#10 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(584): Illuminate\\Foundation\\Exceptions\\RegisterErrorViewPaths->__invoke()
#11 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(565): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()
#12 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(476): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#13 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(354): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#14 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(426): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(ErrorException))
#15 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(114): Illuminate\\Foundation\\Http\\Kernel->renderException(Object(Illuminate\\Http\\Request), Object(ErrorException))
#16 /code/app/laravel/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#17 {main}
"}
[2022-01-27 07:52:13] production.ERROR: Uncaught ReflectionException: Class "view" does not exist in /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:873
Stack trace:
#0 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): ReflectionClass->__construct('view')
#1 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\Container\Container->build('view')
#2 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->resolve('view', Array, true)
#3 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('view', Array)
#4 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\Container\Container->make('view', Array)
#5 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(1420): Illuminate\Foundation\Application->make('view')
#6 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(198): Illuminate\Container\Container->offsetGet('view')
#7 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(166): Illuminate\Support\Facades\Facade::resolveFacadeInstance('view')
#8 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(255): Illuminate\Support\Facades\Facade::getFacadeRoot()
#9 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(18): Illuminate\Support\Facades\Facade::__callStatic('replaceNamespac...', Array)
#10 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(584): Illuminate\Foundation\Exceptions\RegisterErrorViewPaths->__invoke()
#11 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(565): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths()
#12 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(476): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\HttpException))
#13 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(354): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\HttpException))
#14 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Illuminate\Contracts\Container\BindingResolutionException))
#15 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(96): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Illuminate\Contracts\Container\BindingResolutionException))
#16 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Illuminate\Contracts\Container\BindingResolutionException))
#17 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [view] does not exist. in /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:875
Stack trace:
#0 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\Container\Container->build('view')
#1 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->resolve('view', Array, true)
#2 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('view', Array)
#3 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\Container\Container->make('view', Array)
#4 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(1420): Illuminate\Foundation\Application->make('view')
#5 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(198): Illuminate\Container\Container->offsetGet('view')
#6 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(166): Illuminate\Support\Facades\Facade::resolveFacadeInstance('view')
#7 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(255): Illuminate\Support\Facades\Facade::getFacadeRoot()
#8 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(18): Illuminate\Support\Facades\Facade::__callStatic('replaceNamespac...', Array)
#9 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(584): Illuminate\Foundation\Exceptions\RegisterErrorViewPaths->__invoke()
#10 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(565): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths()
#11 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(476): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\HttpException))
#12 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(354): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\HttpException))
#13 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Illuminate\Contracts\Container\BindingResolutionException))
#14 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(96): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Illuminate\Contracts\Container\BindingResolutionException))
#15 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Illuminate\Contracts\Container\BindingResolutionException))
#16 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught ReflectionException: Class \"view\" does not exist in /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:873
Stack trace:
#0 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): ReflectionClass->__construct('view')
#1 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\\Container\\Container->build('view')
#2 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->resolve('view', Array, true)
#3 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\\Foundation\\Application->resolve('view', Array)
#4 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\\Container\\Container->make('view', Array)
#5 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(1420): Illuminate\\Foundation\\Application->make('view')
#6 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(198): Illuminate\\Container\\Container->offsetGet('view')
#7 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(166): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance('view')
#8 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(255): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#9 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(18): Illuminate\\Support\\Facades\\Facade::__callStatic('replaceNamespac...', Array)
#10 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(584): Illuminate\\Foundation\\Exceptions\\RegisterErrorViewPaths->__invoke()
#11 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(565): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()
#12 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(476): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#13 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(354): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#14 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Illuminate\\Contracts\\Container\\BindingResolutionException))
#15 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(96): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Illuminate\\Contracts\\Container\\BindingResolutionException))
#16 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Illuminate\\Contracts\\Container\\BindingResolutionException))
#17 {main}

Next Illuminate\\Contracts\\Container\\BindingResolutionException: Target class [view] does not exist. in /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:875
Stack trace:
#0 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\\Container\\Container->build('view')
#1 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->resolve('view', Array, true)
#2 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\\Foundation\\Application->resolve('view', Array)
#3 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\\Container\\Container->make('view', Array)
#4 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(1420): Illuminate\\Foundation\\Application->make('view')
#5 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(198): Illuminate\\Container\\Container->offsetGet('view')
#6 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(166): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance('view')
#7 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(255): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#8 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(18): Illuminate\\Support\\Facades\\Facade::__callStatic('replaceNamespac...', Array)
#9 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(584): Illuminate\\Foundation\\Exceptions\\RegisterErrorViewPaths->__invoke()
#10 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(565): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()
#11 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(476): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#12 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(354): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#13 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Illuminate\\Contracts\\Container\\BindingResolutionException))
#14 /code/app/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(96): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Illuminate\\Contracts\\Container\\BindingResolutionException))
#15 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Illuminate\\Contracts\\Container\\BindingResolutionException))
#16 {main}
  thrown at /code/app/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:875)
[stacktrace]
#0 {main}
"}
Status: 500 Internal Server Error
X-Powered-By: PHP/8.2.0-dev
Content-type: text/html; charset=UTF-8

Elapsed time: 0.062817 sec

**Comment by pingzhaozz** [comment]
A quick check that the issue is in Laravel app which can't work on PHP 8.1& 8.2

**Comment by kocsismate** [comment]
@pingzhaozz Sorry for forgetting to answer, but I think this issues shouldn't be present anymore. As far as I remember, I upgraded the Laravel app in the meanwhile.

**Comment by kocsismate** [comment]
As mentioned in my previous comment, the issue shouldn't apply anymore. Therefore I'm closing the ticket.
